name: Build and Deploy Maven Package + Docker Image

on:
  push:
    branches:
      - keycloak-gtb
    tags:
      - 'v1.1.0'  # Par exemple v1.1.0

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Configure Maven settings.xml for GitHub Packages
      run: |
        mkdir -p $HOME/.m2
        echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
              xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
              xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\">
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>" > $HOME/.m2/settings.xml

    - name: Build and deploy Maven package
      run: mvn clean deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      env:
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        TAG=${GITHUB_REF##*/}
        TAG=${TAG#refs/tags/}       # nettoyage si ref est un tag
        TAG=${TAG#refs/heads/}      # nettoyage si ref est une branche
        OWNER_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME=ghcr.io/${OWNER_LOWER}/digital-tmp-keycloak-config:$TAG
        echo "Docker image tag: $TAG"
        echo "Docker image name: $IMAGE_NAME"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
