name: Build and Publish Maven Package

on:
  push:
    branches:
      - keycloak-gtb        # déploie snapshots sur cette branche uniquement
  release:
    types: [created]          # déploie sur création de release (=tag)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 and Maven auth for GitHub Packages
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy SNAPSHOT (branch keycloak-gtb)
        if: github.ref == 'refs/heads/keycloak-gtb'
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy RELEASE (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        run: mvn clean deploy -Drevision=${GITHUB_REF#refs/tags/v}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
