name: Build and Deploy Maven Package + Docker Image

on:
  push:
    branches:
      - keycloak-gtb
    tags:
      - 'v1.1.0'  # Déploiement sur tous les tags versionnés commençant par v

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Configure Maven settings.xml for GitHub Packages
      run: |
        mkdir -p $HOME/.m2
        cat > $HOME/.m2/settings.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Build and deploy Maven package
      run: mvn clean deploy --settings $HOME/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/digital-tmp-keycloak-config:${GITHUB_REF##*/}
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
      env:
        GITHUB_REF: ${{ github.ref }}
